### ISSUE TITLE
IllegalArgumentException because accessExternalDTD not supported on the Parser

### ISSUE THREAD

**Issue by marceloprof** [amzn/amazon-pay-sdk-java#38]
Hi!

After the [last commit](https://github.com/amzn/amazon-pay-sdk-java/commit/12ab080d4846ac0d1542e84da351488b759a3fc1) on src/com/amazon/pay/impl/PayLogUtil.java (Line 128)

![image](https://user-images.githubusercontent.com/778243/100214635-6840ee00-2f10-11eb-9e7a-99ee85b15ff4.png)

it generates a IllegalArgumentException calling the com.amazon.pay.response.parser.Parser methods, probably because there the accessExternalDTD has been set as not supported:

![image](https://user-images.githubusercontent.com/778243/100215427-46943680-2f11-11eb-8efa-00e2358e212f.png)

Stacktrace:

`java.lang.IllegalArgumentException: Not supported: http://javax.xml.XMLConstants/property/accessExternalDTD
	at org.apache.xalan.processor.TransformerFactoryImpl.setAttribute(TransformerFactoryImpl.java:571)
	at com.amazon.pay.impl.PayLogUtil.getSanitizedData(PayLogUtil.java:126)
	at com.amazon.pay.impl.PayLogUtil.sanitizeString(PayLogUtil.java:75)
	at com.amazon.pay.response.parser.ResponseData.<init>(ResponseData.java:36)
	at com.amazon.pay.response.parser.GetOrderReferenceDetailsResponseData.<init>(GetOrderReferenceDetailsResponseData.java:30)
	at com.amazon.pay.response.parser.Parser.getOrderReferenceDetails(Parser.java:61)`

**Comment by bjguillot** [comment]
Can you share what version of Java you were running this against, and which XML parsing related jars/libraries you are using?  The changes worked against our internal integration tests.  I'll need to know more about your environment so that we can troubleshoot further.

**Comment by yuki-naki** [comment]
I have same problems of this issues.

because TransformerFactory and Xalan Dependency Conflict
so there have some API cant working 

like [GetAuthorizationDetails ],[CloseAuthorizationRequest]

**Comment by jamesgorrie** [comment]
We have seen this from the same update which was introduced in 3.6.4:
https://github.com/amzn/amazon-pay-sdk-java/compare/3.6.2...3.6.4#diff-d6aa52c278cef70f54019b3ccbbec94e6985cf71dbd86e732d66f9dae9b8ac24R126-R127

We are using:
- JDK: Amazon Corretto v11
- `amazon-pay-java-sdk` v3.7.1

The solution we have settled on is by overriding the `TransformerFactory` class:
https://www.google.com/url?sa=j&url=https%3A%2F%2Fgithub.com%2Fguardian%2Fsupport-frontend%2Fpull%2F5355&uct=1697555454&usg=lbVWXUIxK4Zq4p3bIt-oEfjEWCE.&opi=82159412&source=chat

A Java style implementation of this can be seen here:
https://stackoverflow.com/a/64364531

I do wonder, that given not all Transformers support this if there should be check or similar before setting these properties?
